### ISSUE TITLE
[REQUEST] Just wanted to thank you and feature requests.

### ISSUE THREAD

**Issue by kimjiwongit** [adityam49/Updoot#2]
This project looks wonderful. Personally the code will help me a lot. Thank you so much.

If you are continuing the project, please add gif/video player ability. filter option top --> week, month...

"Load more comments" which is seen on very deep threads are not loaded on clicked.

On double tapping parent comment, few child comments are loaded but "Load more comments" is displayed and it does not show more comments on clicking it.

Please let me know the future of the project and roadmap.

The UI is wonderful. Thank you again.

**Comment by adityam49** [comment]
Appreciate the feedback ✌️,glad that you can make sense of my code 😅.

> Please let me know the future of the project and roadmap.

I do plan to implement all basic features ( browsing , posting and media previews / download ) along with some niche features like offline support and threading watching.  I still lack professional experience so this project is more of learning pet project than a serious competitor to other reddit clients. I am open to suggestions though.

>"Load more comments" which is seen on very deep threads are not loaded on clicked.
 
Reddit's api returns `moreChildren` (load more comments) in a [different way](https://www.reddit.com/r/redditdev/comments/31z6ln/more_children_comments_format_and_schema_issue/) than it does with normal comments. So i'm yet to figure out how I'm going to handle it.

BTW if you don't mind me asking how did you find out this repo anyway? I haven't really posted about it anywhere.

**Comment by kimjiwongit** [comment]
Thanks for your efforts to continue the project further with the  features above, especially it's great you considered offline and download as well.

Ahh. I didn't know about the more children. I have never worked with reddit api. Hope you figure out.

I found the repo through code search on GitHub. I searched reddit Coroutines and found your repo listed. I was specifically looking for MVVM, Coroutines and nested comments view and also upvote/downvote feature handling for learning purpose. Your work was a surprise. 

I am looking forward to updates on repo. Thanks.

**Comment by kimjiwongit** [comment]
Hey, I don't want to interrupt you with messages, but I found this repository https://github.com/person808/ReaderforReddit 

If you run the repo. Make sure, to change background color for comment.xml and view_more.xml to other than white cause the text is white. Author might have forgotten to change.

It implements the working version of moreChildren. Please let me know if this is helpful.

**Comment by adityam49** [comment]
Thanks for the heads-up , this looks promising and I'll look into it 👍.

**Comment by kimjiwongit** [comment]
@adityam49 Are you on social media Instagram, Twitter? I would like to follow you.

**Comment by adityam49** [comment]
You can dm me on Discord @ adityam#8812
