### ISSUE TITLE
Hey, are you taking PRs for this repository?

### ISSUE THREAD

**Issue by Shivamdhuria** [adityam49/Updoot#4]
I would love to contribute if you are.

**Comment by adityam49** [comment]
Contributions are welcome :)

Though at the moment, I am swamped with exams and won't be able to work on this project before the first week of January.

A few details about the project.

- Navigation: It is a mess at the moment.

- UI : All new UI changes are done on compose branch.

- Data : All new features are implemented in master branch and exposed in viewModels. (master is periodically merged with compose branch)

- Testing : I struggle with testing and plan to study and start introducing unit tests in future.

This is playground app for me to learn Android development so I don't have a serious roadmap apart from implementing basic browsing, media viewing , offline support and thread watching.

I would be more than happy to discuss and collaborate on any improvements and features.

**Comment by Shivamdhuria** [comment]
Cool!
I'll start going through the project, and create new issues(for bugs and improvements) when I am done. Can start working on them as you approve.
Does that sound alright?

**Comment by adityam49** [comment]
👍 sound good.

I would also like to mention that UI as of now is not a priority as Compose APIs are not finalized. My plan is to focus on everything below the viewModels (networking, caching, testing) until Compose hits beta.
