### ISSUE TITLE
Improving the puck library usage

### ISSUE THREAD

**Issue by Shivamdhuria** [adityam49/Updoot#7]
1) Use Puck library from Jitpack(I will make it public by tomorrow) instead of using the puck package

2) Currently the view scrolls when fab button is dragged. Ideally I just want it to just scroll when the button is clicked. The draggable part is just an extra feature so you can position the fab button wherever it's convenient for your hand size

https://user-images.githubusercontent.com/10262897/147848826-2e3984cd-6eee-4fe0-8765-6f164db88767.mov

3) saving the latest cordinates of the position of the composable in Shared pref/Datastore. We use this to position the FAB next time where the user left it off.  

4) Update Readme with newer gif, add licence, list all Open source libraries, maintainers, brief about the project etc. 

I will fork this project and make all the above changes. Can send a merge request if you also agree with the above 4 points.

**Comment by adityam49** [comment]
Sounds good to me 👍
